# See config.example.yml for documentation.
name: oot-gc
object: orig/ce-u/main.dol
hash: eaec2d80639095b751c68d9371f7aac7e5c7dbc7
symbols: config/ce-u/symbols.txt
splits: config/ce-u/splits.txt
mw_comment_version: 8

extract:
# xlCoreGCN.c
- symbol: gTgPcTPL
  header: gTgPcTPL.inc
# simGCN.c
- symbol: gcoverOpen
  header: gcoverOpen.inc
- symbol: gnoDisk
  header: gnoDisk.inc
- symbol: gretryErr
  header: gretryErr.inc
- symbol: gfatalErr
  header: gfatalErr.inc
- symbol: gwrongDisk
  header: gwrongDisk.inc
- symbol: greadingDisk
  header: greadingDisk.inc
- symbol: gbar
  header: gbar.inc
- symbol: gyes
  header: gyes.inc
- symbol: gno
  header: gno.inc
- symbol: gmesgOK
  header: gmesgOK.inc
